#-------------------------------
# General Site Settings

title: wellimbharath
logo: 
author: bharath
description: I'm a developer for fun.
email: bharathsh36@gmail.com
phone: +91 86600 83387
address: Nandini Layout, Bangalore, India - 560096

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi!<br>I’m  Bharath  <br> I'm a developer for fun. 

social:
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/bharath-m-493a6b103/"}
- {icon: "ti-stack-overflow", link: "https://stackoverflow.com/users/4800652/bharath?tab=profile"}
#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Young and learning the most as I go along. I code projects and read books most of my time. I occasionally answer question in stackoverflow.            

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Explore the problem statement, look for solutions, plan the development. I take sometime to explore and come up with something concrete."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Share the plan with client, design the solution, start implementation and finish within the agreed deadline."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Setup clean documentation for the work done, deliver the product to client and sit around for further processings. "


# My Team Section
team:

#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Api development, color: '#fdb157', value: '95%'}
- {name: "ML, DL and AI", color: '#fdb157', value: '80%'}
- {name: Blockchain, color: '#bdecf6', value: '60%'}
- {name: Frontend, color: '#9473e6', value: '60%'}
- {name: 'AWS and GCP', color: '#bdecf6', value: '80%'}
- {name: App development, color: '#bdecf6', value: '70%'}
- {name: Devops, color: '#bdecf6', value: '50%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Backend dev - Fulltime, icon: 'icon-1.png', date: 'Feb 2021 - Present', organization: 'Pocketbits'}
- {name: Backend Consultant, icon: 'icon-2.png', date: 'April 2020 - Present', organization: 'Neoscale'}
- {name: Backend Consultant, icon: 'icon-2.png', date: 'December 2020 - Present', organization: 'Pichainlabs'}
- {name: Fullstack Consultant, icon: 'icon-3.png', date: 'October 2020 - Present', organization: 'Flunkey'}
- {name: ML, icon: 'icon-3.png', date: 'May 2021 - June 2021', organization: 'Kutumba.ai'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Backend,
    icon: ti-layout-list-post,
    description: "Write scabale backend code for applications or client's business logic.",
    active: true
  }
- {
    name: Cloud setup,
    icon: ti-linux,
    description: 'Setup proper Vpns, api gateways, metrics and load balances with Aws or GCP.',
    active: false
  }
- {
    name: ML,
    icon: ti-infinite,
    description: 'Build models, train and deploy, setup api endpoints for easy access.',
    active: false
  }
- {
    name: Blockchain,
    icon: ti-link,
    description: 'I can setup nodes and build apis across blockchain protocols and crypto currencies.',
    active: false
  }
- {
    name: Frontend,
    icon: ti-layout-accordion-list,
    description: 'I code the frontend end using tailwind and react. I do not comeup with UI design.',
    active: false
  }





#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "App",
    type : "frontend"
  }
- {
    title : "Backend",
    type : "backend"
  }
- {
    title : "ML",
    type : "ml"
  }

portfolio-items:
  - image : "assets/images/portfolio/pocketbits.png"
    url: "#"
    portfolio-type:
     - type: "frontend"
     - type: "backend"
      
  - image : "assets/images/portfolio/flunkey.png"
    url: "#"
    portfolio-type:
      - type: "frontend"
      - type: "backend"
      
      
  - image : "assets/images/portfolio/kutumba.jpeg"
    url: "#"
    portfolio-type:
      - type: "ml"
      
  - image : "assets/images/portfolio/neoscale.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "backend"
      
  - image : "assets/images/portfolio/pichainlabs.png"
    url: "#"
    portfolio-type:
      - type: "backend"

#-------------------------------
# Testimonials Section

testimonial-items:
  # - name: "Sohail Merchant"
  #   image: "assets/images/testimonial/client-1.png"
  #   designation : "CEO, Pocketbits"
  #   content : "...."

#-------------------------------
# Client Slider Section

client-slider-items:

  - logo: "assets/images/clients-logo/flunkey.jpeg"
    url: "https://dashboard.flunkey.app"

  - logo: "assets/images/clients-logo/neoscale.png"
    url: "https://neoscale-io.webflow.io"
    
  - logo: "assets/images/clients-logo/pichainlabs.png"
    url: "https://pichainlabs.com"
    
  - logo: "assets/images/clients-logo/kutumba.jpeg"
    url: "https://sthana.ai"

  - logo: "assets/images/clients-logo/flunkey.jpeg"
    url: "https://dashboard.flunkey.app"
    
  - logo: "assets/images/clients-logo/neoscale.png"
    url: "https://neoscale-io.webflow.io"
    
  - logo: "assets/images/clients-logo/pichainlabs.png"
    url: "https://pichainlabs.com"
    
#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: bharathsh36@gmail.com
